@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "com.marcobiasone.cinemille.cinemille.controller.MovieController#getPastMovies()",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "*",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "*",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "*",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "com.marcobiasone.cinemille.cinemille.controller.MovieController",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_738899069 { 
   	label=marcobiasone
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1684539231 { 
   	label=cinemille
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_122368889 { 
   	label=GenreMapper
	labeljust=l
	fillcolor=white
	style=filled
   
   GenreMapper1775340387XXXfromEntityToName68688227[
	label="+ fromEntityToName()"
	style=filled
	fillcolor=white
	tooltip="GenreMapper

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_180269926 { 
   	label=MovieMapper
	labeljust=l
	fillcolor=white
	style=filled
   
   MovieMapper1775340387XXXfromEntitytoDTO74534672[
	label="+ fromEntitytoDTO()"
	style=filled
	fillcolor=white
	tooltip="MovieMapper

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1828440469 { 
   	label=ActorMapper
	labeljust=l
	fillcolor=white
	style=filled
   
   ActorMapper1775340387XXXfromEntityToName63093205[
	label="+ fromEntityToName()"
	style=filled
	fillcolor=white
	tooltip="ActorMapper

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_234697536 { 
   	label=MovieServiceImpl
	labeljust=l
	fillcolor=white
	style=filled
   
   MovieServiceImpl1855892845XXXfindAllBeforeDate2122702[
	label="+ findAllBeforeDate()"
	style=filled
	fillcolor=white
	tooltip="MovieServiceImpl

&#10;  Get all the movies already screened before a given date.&#10;  @param beforeDate the given date.&#10;  @return the list of entities.&#10; "
	fontcolor=darkgreen
];
} 

subgraph cluster_850750620 { 
   	label=MovieController
	labeljust=l
	fillcolor=white
	style=filled
   
   MovieController1886703550XXXgetPastMovies0[
	label="+ getPastMovies()"
	style=filled
	fillcolor=white
	tooltip="MovieController

null"
	penwidth=4
	fontcolor=darkgreen
];
} 
} 
} 

'edges    
MovieController1886703550XXXgetPastMovies0 -> MovieMapper1775340387XXXfromEntitytoDTO74534672;
MovieController1886703550XXXgetPastMovies0 -> MovieServiceImpl1855892845XXXfindAllBeforeDate2122702;
MovieMapper1775340387XXXfromEntitytoDTO74534672 -> ActorMapper1775340387XXXfromEntityToName63093205;
MovieMapper1775340387XXXfromEntitytoDTO74534672 -> GenreMapper1775340387XXXfromEntityToName68688227;
    
}
@enduml